
[functions.on-subscriber-created]
enabled = true
verify_jwt = true
import_map = "./functions/on-subscriber-created/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/on-subscriber-created/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/on-subscriber-created/*.html" ]

[functions.confirm-subscriber]
enabled = true
verify_jwt = true
import_map = "./functions/confirm-subscriber/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/confirm-subscriber/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/confirm-subscriber/*.html" ]
